### ISSUE TITLE
Improve android log 

### ISSUE THREAD

**Issue by sytolk** [beansoft/react-native-console#18]
If I press log button and start `react-native log-android`
`/bin/adb logcat *:S ReactNative:V ReactNativeJS:V`
Log from console plugin now is displayed like that:
```
12-02 15:13:23.295  3622  3689 I ReactNativeJS: action %cSET_CONTAINER_ID %c@ 15:13:23.282
12-02 15:13:23.306  3622  3689 I ReactNativeJS: '%c prev state', 'color: #9E9E9E; font-weight: bold', { appReducer: { storeLoaded: true },
12-02 15:13:23.306  3622  3689 I ReactNativeJS:   icards: 
12-02 15:13:23.306  3622  3689 I ReactNativeJS:    [ { identifier: '1001',
```
Is better to parse redux state log and display it the same like [react-native-debugger]( https://github.com/jhen0409/react-native-debugger)
The advantage of `react native console` log is that not need 'Debug JS Remotely' to be started on device to display log. 
I think we can parse and display redux state from Android log like that:

![screenshot_2017-12-02_15-21-52](https://user-images.githubusercontent.com/1415463/33516053-9109f15c-d774-11e7-8aca-ca5090ba7552.png)

**Comment by beansoftapp** [comment]
I've looking into the source code or RN debugger, and it's based on the chrome runtime and written in Node, so this might not be easy to integrate to a Java IDE like IDEA. But your suggestion does make sense, I'll trying to create a standalone log viewer app without using debug mode. And this might be a lot of time to implements it, so please wait.
