### ISSUE TITLE
debugApk目前只是安装一个debugAPk?在编辑器打红色断点不能用啊

### ISSUE THREAD

**Issue by fantasy525** [beansoft/react-native-console#28]
能否支持debugApk后再编辑器打红色断点后能断点调试

**Comment by beansoftapp** [comment]
你好, 这个功能不是简单就能做到的, 我的小插件没法实现. 如果是Webstorm, 已经自带了断点调试功能, 新建运行配置就可以了.

![image](https://user-images.githubusercontent.com/11939450/45334853-3c472580-b5af-11e8-872a-7d25d3518bf1.png)
然后点小虫子调试 我只试过ios的可以 安卓的还木有 应该也支持吧 webstorm那么强大
![image](https://user-images.githubusercontent.com/11939450/45334897-6b5d9700-b5af-11e8-8609-de6d899b9af1.png)

**Comment by fantasy525** [comment]
是的，我目前是这么来的，但是这个方法我发现修改完想要再次测试还得重新安装app?

![tim 20180911104711](https://user-images.githubusercontent.com/22516157/45335047-1b330480-b5b0-11e8-8928-50cd30915085.png)
就是点击箭头所指向的那个按钮。
正常来讲刷新reload一下就可以了吧，然后我还得自己打开dev菜单刷新下然后才能再次进入断点，我发现你的工具有个reload JS,这个不错，另外如果用webstrom自带的那个调试有办法点个什么按钮就Reloadjs的吗？

**Comment by fantasy525** [comment]
我现在是想重新REload的话是进入你的工具点一下 reloadjs

**Comment by beansoftapp** [comment]
... webstorm 默认是没有办法的, 因为这个reload是我自己调研出来的功能. 我倒是可以发一个新版本, 做一个全局的按钮加上快捷键来reload.

**Comment by fantasy525** [comment]
@beansoftapp 可以可以，这个按钮不错，我目前要刷新一下好麻烦，要么自己输入adb shell，要么长按菜单键，太啰嗦了，有个按钮的话就方便很多了，点一下就刷新了，期待

**Comment by beansoftapp** [comment]
@fantasy525 亲 这个功能早就实现了 我都忘了... 菜单: Tools > Android Reload JS 快捷键 command + F2 不过我考虑给主工具栏加个按钮试试

**Comment by beansoftapp** [comment]
Please download https://github.com/beansoftapp/react-native-console/blob/master/react-native-console.jar to test it

增加了主工具栏按钮

**Comment by fantasy525** [comment]
我去，tools下隐藏的很深啊，不过这个快捷键貌似冲突了，我试试这个主按钮哈

**Comment by fantasy525** [comment]
大神，这个按钮在主工具栏？我没找到，请指教
![image](https://user-images.githubusercontent.com/22516157/45336394-f2157280-b5b5-11e8-8fac-29abf53c1aee.png)

**Comment by beansoftapp** [comment]
你的IDEA默认没显示主工具栏 View > Toolbar 切换

**Comment by fantasy525** [comment]
Thanks，I find it,Android ReloadJs button is nice

**Comment by fantasy525** [comment]
你好，首先这个reloadJs的功能很棒，但是用着用着我发现有个体验不太好，就是我点击刷新后会，本来我正在下面看Terminal的rn编译结果呢，结果你的插件界面突然被激活，我还要再重新切换为Terminal界面，能不能我点击reloadJs按钮时在后台执行命令，不要激活RN console的界面呢？
