### ISSUE TITLE
Bug: Unable to run the commandline

### ISSUE THREAD

**Issue by dinukasal** [beansoft/react-native-console#39]
Event log says this(notification also popsup) when running any command(by clicking icons):

React Native Console: Unable to run the commandline:Cannot run program "npm" (in directory "project_folder"): error=2, No such file or directory

Can I set node binary path for terminal used in this console?
Or how to fix this?

Thank you!

**Comment by beansoftapp** [comment]
Normally, if you can run npm in system terminal or command prompt(windows), the plugin will works. I find npm in system PATH envs.

**Comment by Kiarlts** [comment]
+1

**Comment by beansoftapp** [comment]
Do you using the latest RN version 0.62?

**Comment by beansoft** [comment]
due to long inactive of this issue, i'll close it, if you still has problems, you can reopen it at any time.
