### ISSUE TITLE
Android AVD Listing not working.

### ISSUE THREAD

**Issue by sahilchopra0003** [beansoft/react-native-console#43]
<img width="559" alt="Screenshot 2020-02-05 at 12 19 56 PM" src="https://user-images.githubusercontent.com/11456136/73817799-e4e3ce00-4811-11ea-9cf0-8527a7c3b798.png">

**Comment by beansoftapp** [comment]
I've found this issue, but seems a android command line issue, not my plugin's fault.
see https://github.com/ionic-team/ionic/issues/14291
there is a fix script, but i didn't tried yet:

export ANDROID_SDK_ROOT=/Users/[username]/Library/Android/sdk
export PATH=$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools:$PATH
Where [username] is the name of your user folder.

But don't just run those commands or the change won't stay. You should add those lines to your ".bashrc" or ".bash_profile" and after that you need to reload the bash, restart the console or source the edited file, e.g.
"me@localhost:~$ source .bashrc"

But keep in mind those are the folders that worked for me, your system might be using different ones, check the folder before you change anything, you should find there the emulator.

**Comment by troublediehard** [comment]
The emulator path was changed at some point. Now it should be 
/Users/my_user/Library/Android/sdk/**emulator**/emulator
instead of 
/Users/my_user/Library/Android/sdk/**tools**/emulator

**Comment by beansoftapp** [comment]
Thx for your info, i've tried new location, it does work. I'll fix it soon.

**Comment by beansoftapp** [comment]
try this plugin jar first:
https://github.com/beansoftapp/react-native-console/blob/2019.2/react-native-console.jar

**Comment by sahilchopra0003** [comment]
> try this plugin jar first:
> https://github.com/beansoftapp/react-native-console/blob/2019.2/react-native-console.jar

This one is also not working.
The new location is :
/Users/my_user/Library/Android/sdk/emulator
and not
/Users/my_user/Library/Android/sdk/emulator/emulator

**Comment by troublediehard** [comment]
> try this plugin jar first:
> https://github.com/beansoftapp/react-native-console/blob/2019.2/react-native-console.jar

I got this
<img width="402" alt="Screenshot 2020-02-05 at 13 45 28" src="https://user-images.githubusercontent.com/6594232/73839102-dac7cc80-481d-11ea-8e3c-e7ef95984ddc.png">

**Comment by beansoftapp** [comment]
Crate avd can't be done by simply using command line tools, so please open Androd Studio to create one.

**Comment by troublediehard** [comment]
I've already had several AVDs 
<img width="450" alt="Screenshot 2020-02-06 at 11 22 07" src="https://user-images.githubusercontent.com/6594232/73923089-fa6cfc80-48d2-11ea-9a17-c708fd058f1e.png">

**Comment by troublediehard** [comment]
Nevermind, it is working now, probably an additional IDE restart was required.

**Comment by swayok** [comment]
Hi. I'm getting "no Android AVD found" error. 
OS is Windows 10. I have added all required environment variables for Android SDK, emulator and tools. I can run emulator manually using `emulator.exe` but plugin still don't see it. 
Running Android Studio and AVD manager does not help. 
My SDK is placed in E:\AndroidSDK and emulator is in E:\AndroidSDK\emulator
I think that there is something wrong with emulator detection

**Comment by beansoftapp** [comment]
I found the android sdk with following steps:
1. find ANDROID_HOME env
2. or using android/local.properties , there should be a sdk.dir config entry.
Then plus the dir + /emulator.

Can you check your win10 env to see there is a ANDROID_HOME point to the SDK dir?

**Comment by swayok** [comment]
Added ANDROID_HOME env - nothing changed.
Here are my env variables:
ANDROID_HOME - E:\AndroidSDK
ANDROID_SDK_ROOT - E:\AndroidSDK
PATH - E:\AndroidSDK\emulator;E:\AndroidSDK\tools;E:\AndroidSDK\platform-tools
Maybe it would be easier to configure SDK path from Welcome screen?

**Comment by stephanoparaskeva** [comment]
<img width="469" alt="Screenshot 2020-04-20 at 22 12 48" src="https://user-images.githubusercontent.com/40718272/79800435-1b7eae80-8354-11ea-94b4-cfbfcee3838a.png">

Why am I getting this, I already have the AVD?

**Comment by beansoftapp** [comment]
Please try the latest plugin 
https://github.com/beansoftapp/react-native-console/blob/2019.2/react-native-console.jar

I've try to find emulator from PATH env first, then through the config files.
With this version, can fix this by:
sudo ln -s /Users/my_user/Library/Android/sdk/emulator /usr/bin/emulator
