### ISSUE TITLE
Multiple icons on the console

### ISSUE THREAD

**Issue by xenos28** [beansoft/react-native-console#51]
React Native Console version: 2020.3.0

IntelliJ IDEA 2020.2.2 (Ultimate Edition)
Build #IU-202.7319.50, built on September 15, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.50-amd64-desktop

With longer work with the project and frequent use of the options from the console "Android Dev Menu" and "Android Reload JS", there is a problem that the icons in new tabs start to duplicate.
IDEA does not throw errors in the log.
How to fix this?

![Zrzut ekranu Deepin_wybierz-obszar_20201005122145](https://user-images.githubusercontent.com/7773479/95068702-e994b500-0705-11eb-8335-633337d2f585.png)

**Comment by beansoft** [comment]
Thanks for your report, I'll take a look at.

**Comment by beansoft** [comment]
I can reproduced it when click "Android Dev Menu", will fix it ASAP.

**Comment by beansoft** [comment]
@xenos28 I've update a new release which fixed this issue and is pending JetBrains' approval.
You can download and install it directly for a test:

https://plugins.jetbrains.com/files/9564/98722/react-native-console_release.jar?updateId=98722&pluginId=9564&family=INTELLIJ

**Comment by beansoft** [comment]
https://plugins.jetbrains.com/files/9564/98723/react-native-console_release.jar?updateId=98723&pluginId=9564&family=INTELLIJ

Using this one instead.

**Comment by xenos28** [comment]
> https://plugins.jetbrains.com/files/9564/98723/react-native-console_release.jar?updateId=98723&pluginId=9564&family=INTELLIJ
> 
> Using this one instead.

Thanks! The uploaded file resolved the problem.
Now just wait for the official update
