### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by BokiGaja** [beansoft/react-native-console#63]
Hi, I've got this error while using this plugin in Webstorm
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of com/github/beansoft/ios/IosSchemeService.getInstance must not be null
	at com.github.beansoft.ios.IosSchemeService.$$$reportNull$$$0(Unknown Source)
	at com.github.beansoft.ios.IosSchemeService.getInstance(Unknown Source)
	at com.github.beansoft.C.A.H.ā(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

NOTE: The plugin still works properly, but I just want to inform you that this issue occurred a couple of times

**Comment by beansoft** [comment]
Thx for the report, I’ve noticed this problme and a fix with a new version already is in progress.

**Comment by beansoft** [comment]
should be fixed in this new release, please give a try

**Comment by BokiGaja** [comment]
Seems like this problem doesn't exist in a new version. Thanks
